# Generated by Django 4.2.16 on 2026-04-02 13:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=5)),
                ('class_teacher', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['class_teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stream__order', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('relation', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], default='guardian', max_length=20)),
                ('phone_primary', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id_number', models.CharField(blank=True, help_text='National ID or Passport', max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('kcpe_index', models.CharField(blank=True, help_text='KCPE Index Number', max_length=20)),
                ('kcpe_marks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nemis_no', models.CharField(blank=True, help_text='NEMIS UPI Number', max_length=20)),
                ('date_admitted', models.DateField()),
                ('boarding_type', models.CharField(choices=[('day', 'Day Scholar'), ('boarding', 'Boarding')], default='day', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('medical_notes', models.TextField(blank=True)),
                ('special_needs', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.classsection')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.guardian')),
            ],
            options={
                'ordering': ['class_section', 'last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='classsection',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.stream'),
        ),
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('stream', 'section')},
        ),
    ]
