# Generated by Django 4.2.16 on 2026-04-02 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsc_number', models.CharField(blank=True, help_text='TSC Registration Number', max_length=30)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('employment_status', models.CharField(choices=[('tsc', 'TSC Employed'), ('bom', 'BOM Employed'), ('intern', 'Teaching Intern'), ('support', 'Support Staff')], default='tsc', max_length=20)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, help_text='e.g. B.Ed Science, PGDE', max_length=120)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=80)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=80)),
                ('bank_account', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('subjects_taught', models.ManyToManyField(blank=True, related_name='staff', to='exams.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name'],
            },
        ),
    ]
