# Generated by Django 4.2.16 on 2026-04-02 13:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('opener', 'Opener'), ('mid', 'Mid-Term'), ('end', 'End of Term'), ('mock', 'Mock / Trial'), ('internal', 'Internal Assessment')], default='end', max_length=20)),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('year', models.PositiveSmallIntegerField()),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Visible to parents when published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('streams', models.ManyToManyField(blank=True, related_name='exams', to='students.stream')),
            ],
            options={
                'ordering': ['-year', '-term', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('curriculum', models.CharField(choices=[('kcse', 'KCSE (8-4-4)'), ('cbc', 'CBC')], default='kcse', max_length=10)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('max_score', models.PositiveSmallIntegerField(default=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='students.classsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__in': ['subject_teacher', 'class_teacher', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['class_section', 'subject'],
                'unique_together': {('teacher', 'subject', 'class_section')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_absent', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.subject')),
            ],
            options={
                'ordering': ['student__last_name', 'subject__order'],
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
    ]
