# Generated by Django 4.2.16 on 2026-04-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('icon', models.CharField(default='bi-box-seam', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Inventory Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor / Damaged'), ('lost', 'Lost')], default='good', max_length=10)),
                ('location', models.CharField(blank=True, help_text='e.g. Science Lab, Library', max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=60)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('value_kes', models.DecimalField(blank=True, decimal_places=2, help_text='Approximate value in KSh', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
    ]
