# Generated by Django 4.2.16 on 2026-04-02 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('objectives', models.TextField(blank=True, help_text='Learning objectives for this unit')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('stream', models.ForeignKey(help_text='Which form/grade this unit applies to', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='students.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='exams.subject')),
            ],
            options={
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(help_text='Week of term (1–14)')),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('year', models.PositiveSmallIntegerField()),
                ('topic', models.CharField(max_length=160)),
                ('objectives', models.TextField(help_text='What students will be able to do by end of lesson')),
                ('content_outline', models.TextField(help_text='Key content points to cover')),
                ('teaching_methods', models.CharField(blank=True, help_text='e.g. Discussion, Experiment, Demo', max_length=200)),
                ('resources', models.TextField(blank=True, help_text='Textbooks, lab equipment, charts, etc.')),
                ('assessment', models.TextField(blank=True, help_text='How learning will be assessed')),
                ('remarks', models.TextField(blank=True, help_text='Post-lesson reflections (fill after the lesson)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='students.classsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='exams.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__in': ['subject_teacher', 'class_teacher', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.syllabusunit')),
            ],
            options={
                'ordering': ['-year', '-term', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='TopicCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('year', models.PositiveSmallIntegerField()),
                ('is_covered', models.BooleanField(default=False)),
                ('date_covered', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='students.classsection')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_records', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='lessons.syllabusunit')),
            ],
            options={
                'ordering': ['unit__order'],
                'unique_together': {('unit', 'class_section', 'term', 'year')},
            },
        ),
    ]
